// Copied from viewer/src/core/parser/lines.ts by hud/scripts/sync-core.mjs.
// Do not edit this file: change the source, then run the script again.
/**
 * Line-level helpers shared by the phase-file parsers.
 *
 * Every parser works on {@link SourceLine}s rather than bare strings so that
 * each piece of the model, and each warning, can point back at its 1-based
 * line in the original file.
 */
import type { Warning } from '../model.js';

/** One line of the input, without its line ending. */
export interface SourceLine {
  /** The line exactly as read (no `\n` / `\r\n`). */
  text: string;
  /** 1-based line number in the file. */
  line: number;
}

/**
 * Split text into lines, tolerating LF and CRLF endings and a leading BOM.
 * The result always has at least one line (an empty input is one empty line).
 */
export function splitLines(text: string): SourceLine[] {
  const body = text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
  const parts = body.split(/\r?\n/);
  // A trailing newline leaves one empty last part; it is not a real line.
  if (parts.length > 1 && parts[parts.length - 1] === '') parts.pop();
  return parts.map((t, i) => ({ text: t, line: i + 1 }));
}

/** Build a {@link Warning} about one line (or the whole file when `at` is `null`). */
export function warningAt(file: string, at: SourceLine | null, message: string): Warning {
  return at ? { file, line: at.line, raw: at.text, message } : { file, line: 0, raw: '', message };
}

/** `true` for an empty or whitespace-only line. */
export function isBlank(line: SourceLine): boolean {
  return line.text.trim() === '';
}

/** `true` for a markdown thematic break made of dashes (`---`, `- - -`, `-----`). */
export function isDivider(line: SourceLine): boolean {
  return /^ {0,3}(?:-\s*){3,}$/.test(line.text);
}

/**
 * Drop leading blank lines and trailing blank / `---` divider lines, so a
 * section's body ends at its last line of real content.
 */
export function trimBlock(lines: SourceLine[]): SourceLine[] {
  let start = 0;
  let end = lines.length;
  while (start < end && isBlank(lines[start]!)) start++;
  while (end > start && (isBlank(lines[end - 1]!) || isDivider(lines[end - 1]!))) end--;
  return lines.slice(start, end);
}

/** Join lines back into text. */
export function joinLines(lines: SourceLine[]): string {
  return lines.map((l) => l.text).join('\n');
}

/**
 * Control characters (other than tab), DEL, and U+FFFD (what invalid UTF-8
 * decodes to) never belong in a phase file.
 */
const JUNK = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F�]/;

/** `true` when the line holds stray binary bytes or invalid UTF-8. */
export function hasJunkBytes(line: SourceLine): boolean {
  return JUNK.test(line.text);
}
