// Copied from viewer/src/core/parser/sections.ts by hud/scripts/sync-core.mjs.
// Do not edit this file: change the source, then run the script again.
/**
 * Parsers for the list-shaped sprint sections: `### Acceptance Criteria` and
 * `### Dependencies`, plus the markdown list reader that
 * `### Verification` (see `verification.ts`) shares.
 *
 * Pure and never throws. Neither section produces warnings: any bullet is a
 * valid criterion, and a dependency bullet that names no sprint or phase is
 * kept as prose. Whether a named sprint or phase exists is checked later, by
 * `loadProject`, which sees every phase file.
 */
import type { AcceptanceCriterion, Dependency } from '../model.js';
import { isBlank, type SourceLine } from './lines.js';

/** One item of a markdown list (or a stand-alone paragraph line) inside a section. */
export interface ListItem {
  /** Item text without the bullet marker, trimmed. Continuation lines are joined on with a single space. */
  text: string;
  /** `true` when the item starts with a bullet (`-`, `*`, `+`, `1.`, `1)`); `false` for a plain paragraph line. */
  bullet: boolean;
  /** Leading whitespace width of the item's first line (a tab counts as 4). Nested bullets have a larger indent. */
  indent: number;
  /** The item's first line. */
  line: SourceLine;
}

const BULLET = /^(\s*)(?:[-*+]|\d{1,9}[.)])(?:\s+(.*))?$/;
/** A thematic break of dashes, asterisks or underscores (`---`, `* * *`, `___`). */
const THEMATIC_BREAK = /^ {0,3}([-*_])(?:[ \t]*\1){2,}[ \t]*$/;
const CHECKBOX = /^\[([ xX])\](?:\s+|$)(.*)$/;

function indentOf(text: string): number {
  let width = 0;
  for (const ch of text) {
    if (ch === ' ') width += 1;
    else if (ch === '\t') width += 4;
    else break;
  }
  return width;
}

/**
 * Read a section body as a flat list of items, in file order.
 *
 * - Every bullet starts a new item, at any nesting depth (nested bullets are
 *   flattened; {@link ListItem.indent} tells them apart).
 * - A non-bullet line indented deeper than the current item continues it
 *   (joined with a space), even after a blank line. Any other non-bullet line
 *   starts a paragraph item of its own, so bullet-less lines such as
 *   `cli: npm test` / `skip-ui: true` stay separate. (Markdown's lazy
 *   continuation, an unindented line gluing onto the item above, is
 *   deliberately not followed.)
 * - Blank lines and thematic breaks (`---`) are skipped; a break also ends
 *   the current item.
 * - Items whose text ends up empty (a bare `-`) are dropped.
 */
export function parseListItems(lines: SourceLine[]): ListItem[] {
  const items: ListItem[] = [];
  let current: ListItem | null = null;

  for (const line of lines) {
    if (isBlank(line)) continue;
    if (THEMATIC_BREAK.test(line.text)) {
      current = null;
      continue;
    }

    const indent = indentOf(line.text);
    const bullet = BULLET.exec(line.text);
    if (bullet) {
      current = { text: (bullet[2] ?? '').trim(), bullet: true, indent, line };
      items.push(current);
    } else if (current !== null && indent > current.indent) {
      const more = line.text.trim();
      current.text = current.text === '' ? more : `${current.text} ${more}`;
    } else {
      current = { text: line.text.trim(), bullet: false, indent, line };
      items.push(current);
    }
  }

  return items.filter((item) => item.text !== '');
}

/**
 * Parse a `### Acceptance Criteria` body. Every list item (and any stray
 * paragraph line) becomes one criterion. A leading checkbox (`[ ]`, `[x]`,
 * `[X]`) on a bullet is stripped into {@link AcceptanceCriterion.checked}.
 */
export function parseAcceptanceCriteria(lines: SourceLine[]): AcceptanceCriterion[] {
  const criteria: AcceptanceCriterion[] = [];
  for (const item of parseListItems(lines)) {
    let text = item.text;
    let checked: boolean | null = null;
    const box = item.bullet ? CHECKBOX.exec(text) : null;
    if (box) {
      checked = box[1] !== ' ';
      text = (box[2] ?? '').trim();
    }
    // A bare checkbox with no text says nothing.
    if (text === '') continue;
    criteria.push({ text, checked, line: item.line.line });
  }
  return criteria;
}

/** List separators allowed between ids after one `Sprint` / `Phase` word: `,` `&` `/` `and` `or`. */
const SEP = String.raw`\s*(?:,|&|/|\band\b|\bor\b)\s*`;
const SPRINT_ID = String.raw`\d+\.\d+(?!\d|\.\d)`;
const PHASE_ID = String.raw`\d+(?!\d|\.\d)`;
/** `Sprint 1.2`, `Sprints 1.2 and 1.3`, `Sprint 1.2, 1.3`, `Sprint #1.2`. */
const SPRINT_REF = new RegExp(String.raw`\bsprints?\s*#?\s*(${SPRINT_ID}(?:${SEP}${SPRINT_ID})*)`, 'gi');
/** `Phase 1`, `Phases 1 and 2`, `Phase 1, 2`. Never `Phase 1.2`. */
const PHASE_REF = new RegExp(String.raw`\bphases?\s*#?\s*(${PHASE_ID}(?:${SEP}${PHASE_ID})*)`, 'gi');
const NONE = /^(?:none|n\/a|no dependencies|nothing)\b/i;
const DASH_ONLY = /^[—–-]+$/;

/**
 * The part of a dependency bullet that is scanned for ids: inline code spans
 * and parenthesized notes removed, so `Sprint 1.3 (needs the Phase 2 schema)`
 * names only Sprint 1.3.
 */
export function dependencyScanText(text: string): string {
  let s = text.replace(/`[^`]*`/g, ' ');
  let prev = '';
  while (prev !== s) {
    prev = s;
    s = s.replace(/\([^()]*\)/g, ' ');
  }
  // An unclosed "(" runs to the end of the bullet.
  return s.replace(/\([^)]*$/, ' ');
}

function pushUnique<T>(list: T[], value: T): void {
  if (!list.includes(value)) list.push(value);
}

/**
 * Pull the sprint and phase ids out of one dependency bullet.
 *
 * - `Sprint X.Y` (or `Sprints X.Y and X.Z`, `Sprint X.Y, X.Z`) adds sprint ids.
 * - `Phase N` (or `Phases N and M`) adds whole-phase ids.
 * - A bare `X.Y` with no `Sprint` word in front of its list is not an id
 *   (it's too easily a version number or a measurement).
 * - Text in parentheses and inside inline code is a note and never scanned.
 * - Ids are kept in order of first mention, without duplicates.
 */
export function extractDependencyRefs(text: string): { sprints: string[]; phases: number[] } {
  const scan = dependencyScanText(text);
  const sprints: string[] = [];
  const phases: number[] = [];
  for (const m of scan.matchAll(SPRINT_REF)) {
    for (const id of (m[1] ?? '').match(/\d+\.\d+/g) ?? []) pushUnique(sprints, id);
  }
  for (const m of scan.matchAll(PHASE_REF)) {
    for (const n of (m[1] ?? '').match(/\d+/g) ?? []) pushUnique(phases, Number(n));
  }
  return { sprints, phases };
}

/**
 * Parse a `### Dependencies` body. Every list item (and any stray paragraph
 * line) becomes one {@link Dependency}, its ids pulled out by
 * {@link extractDependencyRefs}. A bullet that says `None` (or `N/A`,
 * `No dependencies`, a lone dash) and names no id is `none: true`.
 */
export function parseDependencies(lines: SourceLine[]): Dependency[] {
  return parseListItems(lines).map((item) => {
    const { sprints, phases } = extractDependencyRefs(item.text);
    const bare = dependencyScanText(item.text).trim();
    const none = sprints.length === 0 && phases.length === 0 && (NONE.test(bare) || DASH_ONLY.test(bare));
    return { raw: item.text, sprints, phases, none, line: item.line.line };
  });
}
