// Copied from viewer/src/core/parser/tasks.ts by hud/scripts/sync-core.mjs.
// Do not edit this file: change the source, then run the script again.
/**
 * Task-table parsing for one sprint's `### Tasks` section.
 *
 * Columns are mapped from the header row, so the canonical
 * `Status | # | Task | Module | Reference`, the legacy `# | Task | Module | Reference`
 * (no Status column) and the rare `Status | # | Task | Reference` all work.
 *
 * Rows may omit trailing cells (phase-planner's sparse-row rule). A row that
 * stops right after the Module column, while the header also has a Reference
 * column right after it, is ambiguous: `| — | 4 | Task | docs/x.md |` is a
 * Reference-only row, `| — | 2 | Task | src/x.ts |` a Module-only row. The cell's
 * shape decides (see {@link looksLikeDoc}).
 *
 * Never throws. Problems become warnings on the offending line.
 */
import type { ParseResult, Task, TaskStatus, Warning } from '../model.js';
import { isBlank, warningAt, type SourceLine } from './lines.js';
import { normalizeStatus } from './status.js';

/** A logical task-table column. */
export type TaskColumn = 'status' | 'number' | 'task' | 'module' | 'reference';

/** What {@link parseTaskTable} extracts from a `### Tasks` section. */
export interface TaskTable {
  /** Rows in file order. */
  tasks: Task[];
  /** `true` when the table has no Status column. */
  legacyTable: boolean;
}

/** One table row split into cells. */
export interface SplitRow {
  /** Cell contents, untrimmed, with `\|` unescaped to `|`. */
  cells: string[];
  /** `false` when the row does not end with a pipe. */
  closed: boolean;
}

/** Column order assumed when the header can't be read. */
const CANONICAL: readonly TaskColumn[] = ['status', 'number', 'task', 'module', 'reference'];

const HEADER_NAMES = new Map<string, TaskColumn>([
  ['status', 'status'],
  ['state', 'status'],
  ['#', 'number'],
  ['no', 'number'],
  ['num', 'number'],
  ['number', 'number'],
  ['id', 'number'],
  ['task', 'task'],
  ['tasks', 'task'],
  ['description', 'task'],
  ['module', 'module'],
  ['modules', 'module'],
  ['file', 'module'],
  ['files', 'module'],
  ['path', 'module'],
  ['reference', 'reference'],
  ['references', 'reference'],
  ['ref', 'reference'],
  ['refs', 'reference'],
  ['spec', 'reference'],
  ['doc', 'reference'],
  ['docs', 'reference'],
]);

/** Cell values that mean "no module / no reference". */
const PLACEHOLDERS = new Set(['', '—', '–', '-']);

/** `true` when a line looks like a table row (starts with `|`). */
export function isTableRow(line: SourceLine): boolean {
  return line.text.trimStart().startsWith('|');
}

/**
 * Mark which characters of `s` sit inside an inline code span. A backtick run
 * opens a span only when a run of the same length closes it later on the line;
 * otherwise the backticks are literal.
 */
function codeSpanMask(s: string): boolean[] {
  const mask: boolean[] = new Array<boolean>(s.length).fill(false);
  const runLength = (at: number): number => {
    let n = 0;
    while (s[at + n] === '`') n++;
    return n;
  };
  let i = 0;
  while (i < s.length) {
    if (s[i] === '\\') {
      i += 2;
      continue;
    }
    if (s[i] !== '`') {
      i++;
      continue;
    }
    const open = runLength(i);
    let j = i + open;
    let close = -1;
    while (j < s.length) {
      if (s[j] === '`') {
        const n = runLength(j);
        if (n === open) {
          close = j;
          break;
        }
        j += n;
      } else {
        j++;
      }
    }
    if (close < 0) {
      i += open;
      continue;
    }
    for (let k = i; k < close + open; k++) mask[k] = true;
    i = close + open;
  }
  return mask;
}

/**
 * Split a markdown table row into cells. Escaped pipes (`\|`) and pipes inside
 * inline code never split a cell; `\|` is unescaped to `|` in the cell text.
 */
export function splitRow(text: string): SplitRow {
  let s = text.trim();
  if (s.startsWith('|')) s = s.slice(1);
  const code = codeSpanMask(s);
  const cells: string[] = [];
  let cur = '';
  let closed = false;
  for (let i = 0; i < s.length; i++) {
    const ch = s[i]!;
    if (ch === '\\' && s[i + 1] === '|') {
      cur += '|';
      i++;
      continue;
    }
    if (ch === '|' && !code[i]) {
      cells.push(cur);
      cur = '';
      if (i === s.length - 1) closed = true;
      continue;
    }
    cur += ch;
  }
  if (!closed) cells.push(cur);
  return { cells, closed };
}

/** `true` for a header separator row such as `|---|:--:|---|`. */
export function isSeparatorRow(cells: string[]): boolean {
  return cells.length > 0 && cells.every((c) => /^\s*:?-+:?\s*$/.test(c));
}

/**
 * `true` when a cell looks like a document rather than code: it ends in
 * `.md`, `.markdown`, `.html`, `.htm` or `.txt` (ignoring a `#fragment`), or
 * lives under `docs/`.
 */
export function looksLikeDoc(cell: string): boolean {
  const p = cell
    .trim()
    .replace(/^`+|`+$/g, '')
    .trim()
    .replace(/^\.\//, '');
  const path = p.split('#')[0] ?? '';
  return /^docs\//i.test(p) || /\.(md|markdown|html?|txt)$/i.test(path);
}

function normalizeHeader(cell: string): string {
  return cell
    .replace(/[*_`]/g, '')
    .trim()
    .replace(/\.$/, '')
    .toLowerCase();
}

function pathCell(cell: string | null): string | null {
  return cell === null || PLACEHOLDERS.has(cell) ? null : cell;
}

/**
 * Parse the first markdown table in a `### Tasks` section. Lines before the
 * table are ignored; the table ends at the first line that isn't a row.
 * Returns no tasks (and no warnings) when the section has no table.
 */
export function parseTaskTable(lines: SourceLine[], file: string): ParseResult<TaskTable> {
  const warnings: Warning[] = [];
  const tasks: Task[] = [];
  const start = lines.findIndex(isTableRow);
  if (start < 0) return { value: { tasks, legacyTable: false }, warnings };

  const headerLine = lines[start]!;
  const header = splitRow(headerLine.text);
  let columns: readonly (TaskColumn | null)[];
  let i = start + 1;

  if (isSeparatorRow(header.cells)) {
    warnings.push(warningAt(file, headerLine, 'Task table has no header row; columns read in the canonical order'));
    columns = CANONICAL;
  } else {
    const mapped = header.cells.map((c) => HEADER_NAMES.get(normalizeHeader(c)) ?? null);
    if (mapped.includes('task')) {
      columns = mapped;
    } else {
      warnings.push(
        warningAt(file, headerLine, 'Task table header has no Task column; columns read in the canonical order'),
      );
      columns = CANONICAL;
    }
    const sep = lines[i];
    if (sep && isTableRow(sep) && isSeparatorRow(splitRow(sep.text).cells)) {
      i++;
    } else {
      warnings.push(warningAt(file, headerLine, 'Task table header is not followed by a separator row'));
    }
  }

  const legacyTable = !columns.includes('status');
  const idx = (col: TaskColumn): number => columns.indexOf(col);
  const moduleIdx = idx('module');
  const referenceIdx = idx('reference');

  for (; i < lines.length; i++) {
    const line = lines[i]!;
    if (!isTableRow(line)) {
      if (!isBlank(line)) {
        warnings.push(
          warningAt(file, line, 'Text directly after the task table with no blank line (markdown reads it as a table row)'),
        );
      }
      break;
    }

    const row = splitRow(line.text);
    const cells = row.cells.map((c) => c.trim());
    if (isSeparatorRow(row.cells) || cells.every((c) => c === '')) continue;

    if (!row.closed) warnings.push(warningAt(file, line, 'Table row has no closing pipe'));
    if (cells.length > columns.length) {
      warnings.push(
        warningAt(
          file,
          line,
          `Table row has ${cells.length} cells but the header has ${columns.length}; extra cells ignored`,
        ),
      );
    }

    const get = (col: TaskColumn): string | null => {
      const at = idx(col);
      return at >= 0 && at < cells.length ? (cells[at] ?? null) : null;
    };

    let status: TaskStatus = 'todo';
    let rawStatus: string | null = null;
    if (!legacyTable) {
      rawStatus = get('status') ?? '';
      const normalized = normalizeStatus(rawStatus);
      status = normalized.status;
      if (!normalized.recognized) {
        warnings.push(warningAt(file, line, `Unrecognized status "${rawStatus}"; task kept with status unknown`));
      }
    }

    const numberCell = get('number');
    const text = get('task');
    if (text === null) warnings.push(warningAt(file, line, 'Table row has no Task cell'));

    let moduleCell = get('module');
    let referenceCell = get('reference');
    // Sparse 4-cell form: the row stops at the Module column, so its last cell
    // may really be a Reference. Decide by shape.
    if (
      moduleIdx >= 0 &&
      referenceIdx === moduleIdx + 1 &&
      cells.length === referenceIdx &&
      moduleCell !== null &&
      looksLikeDoc(moduleCell)
    ) {
      referenceCell = moduleCell;
      moduleCell = null;
    }

    tasks.push({
      number: numberCell !== null && /^\d+$/.test(numberCell) ? Number(numberCell) : null,
      text: text ?? '',
      status,
      rawStatus,
      legacy: legacyTable,
      module: pathCell(moduleCell),
      reference: pathCell(referenceCell),
      line: line.line,
    });
  }

  return { value: { tasks, legacyTable }, warnings };
}
