#!/usr/bin/env node
/**
 * Copies the viewer's pure core modules into the HUD mod.
 *
 * The mod reads phase files and run logs with the same parser and derive code
 * as phase-viewer. A mod can only import files from its own folder, so the
 * modules are copied from `viewer/src/core/` into `hud/hooks/core/`. This
 * script is the only thing that writes that folder, and it never writes
 * anywhere else: `viewer/` is read, not changed.
 *
 *   node hud/scripts/sync-core.mjs           write the copy
 *   node hud/scripts/sync-core.mjs --check   exit 1 when the copy differs from the source
 *
 * What gets copied: every `.ts` file under `parser/` and `derive/`, the run-log
 * reader, and whatever those import by relative path (the model types). A file
 * that imports anything else (a `node:` module, a package) stops the script,
 * because a mod's hooks module has no Node.
 *
 * Each copy is the source with a two-line header and LF line endings.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HUD_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REPO_ROOT = path.resolve(HUD_ROOT, '..');
const SOURCE = path.join(REPO_ROOT, 'viewer', 'src', 'core');
const TARGET = path.join(HUD_ROOT, 'hooks', 'core');

/** Folders copied whole, and single files, relative to `viewer/src/core/`. */
const ENTRY_DIRS = ['parser', 'derive'];
const ENTRY_FILES = ['runlog/read.ts'];

const IMPORT = /^\s*(?:import|export)\b[^'"]*?\bfrom\s*['"]([^'"]+)['"]|^\s*import\s*['"]([^'"]+)['"]/gm;

/** Forward-slash path relative to `viewer/src/core/`. */
function rel(file) {
  return path.relative(SOURCE, file).split(path.sep).join('/');
}

function tsFilesIn(dir) {
  const out = [];
  for (const name of readdirSync(dir).sort()) {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) out.push(...tsFilesIn(full));
    else if (name.endsWith('.ts') && !name.endsWith('.test.ts')) out.push(full);
  }
  return out;
}

/** The files to copy: the entries plus everything they import, as `relative path → source text`. */
function collect() {
  const queue = [
    ...ENTRY_DIRS.flatMap((dir) => tsFilesIn(path.join(SOURCE, dir))),
    ...ENTRY_FILES.map((file) => path.join(SOURCE, file)),
  ];
  const files = new Map();
  while (queue.length > 0) {
    const file = queue.shift();
    const key = rel(file);
    if (files.has(key)) continue;
    if (key.startsWith('..')) throw new Error(`${key} is outside viewer/src/core/`);
    const text = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
    files.set(key, text);
    for (const match of text.matchAll(IMPORT)) {
      const spec = match[1] ?? match[2];
      if (!spec.startsWith('.')) {
        throw new Error(`viewer/src/core/${key} imports "${spec}". Only relative imports can be copied into a mod.`);
      }
      queue.push(path.resolve(path.dirname(file), spec.replace(/\.js$/, '.ts')));
    }
  }
  return files;
}

function withHeader(key, text) {
  return (
    `// Copied from viewer/src/core/${key} by hud/scripts/sync-core.mjs.\n` +
    `// Do not edit this file: change the source, then run the script again.\n` +
    text
  );
}

/** Every `.ts` file now in `hud/hooks/core/`, as forward-slash paths relative to it. */
function existing() {
  if (!existsSync(TARGET)) return [];
  return tsFilesIn(TARGET).map((file) => path.relative(TARGET, file).split(path.sep).join('/'));
}

function main() {
  const check = process.argv.includes('--check');
  const expected = new Map([...collect()].map(([key, text]) => [key, withHeader(key, text)]));
  const present = existing();
  const stale = present.filter((key) => !expected.has(key));

  if (check) {
    const problems = [];
    for (const [key, text] of expected) {
      const file = path.join(TARGET, key);
      if (!existsSync(file)) problems.push(`missing: hud/hooks/core/${key}`);
      else if (readFileSync(file, 'utf8').replace(/\r\n/g, '\n') !== text) problems.push(`differs: hud/hooks/core/${key}`);
    }
    for (const key of stale) problems.push(`not in the source: hud/hooks/core/${key}`);
    if (problems.length > 0) {
      console.error('hud/hooks/core/ has drifted from viewer/src/core/:');
      for (const problem of problems) console.error(`  ${problem}`);
      console.error('Run: node hud/scripts/sync-core.mjs');
      process.exit(1);
    }
    console.log(`hud/hooks/core/ matches viewer/src/core/ (${expected.size} files).`);
    return;
  }

  for (const key of stale) rmSync(path.join(TARGET, key));
  for (const [key, text] of expected) {
    const file = path.join(TARGET, key);
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, text);
  }
  console.log(`Wrote ${expected.size} files to hud/hooks/core/${stale.length > 0 ? `, removed ${stale.length}` : ''}.`);
}

try {
  main();
} catch (err) {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
}
